// SIDEBAR
export const OPEN_SIDEBAR = "OPEN_SIDEBAR";
export const CLOSE_SIDEBAR = "CLOSE_SIDEBAR";

// BLOG
export const GET_BLOG_BEGIN = "GET_BLOG_BEGIN";
export const GET_BLOG_SUCCESS = "GET_BLOG_SUCCESS";
export const GET_BLOG_ERROR = "GET_BLOG_ERROR";

// SINGLE BLOG
export const GET_SINGLE_BLOG_BEGIN = "GET_SINGLE_BLOG_BEGIN";
export const GET_SINGLE_BLOG_SUCCESS = "GET_SINGLE_BLOG_SUCCESS";
export const GET_SINGLE_BLOG_ERROR = "GET_SINGLE_BLOG_ERROR";

// SEARCHTERM
export const GET_BLOG_BY_SEARCHTERM_BEGIN = "GET_BLOG_BY_SEARCHTERM_BEGIN";
export const GET_BLOG_BY_SEARCHTERM_SUCCESS = "GET_BLOG_BY_SEARCHTERM_SUCCESS";
export const GET_BLOG_BY_SEARCHTERM_ERROR = "GET_BLOG_BY_SEARCHTERM_ERROR";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";

export const SET_PAGE_COUNT = "SET_PAGE_COUNT";

// USER
export const GET_SINGLE_USER_BEGIN = "GET_SINGLE_USER_BEGIN";
export const GET_SINGLE_USER_SUCCESS = "GET_SINGLE_USER_SUCCESS";
export const GET_SINGLE_USER_ERROR = "GET_SINGLE_USER_ERROR";

// COMMENT
export const GET_COMMENT_BY_POST_BEGIN = "GET_COMMENT_BY_POST_BEGIN";
export const GET_COMMENT_BY_POST_SUCCESS = "GET_COMMENT_BY_POST_SUCCESS";
export const GET_COMMENT_BY_POST_ERROR = "GET_COMMENT_BY_POST_ERROR";

// URL
export const BLOG_URL = "posts";
export const SEARCH_URL = "posts/search?q=";
export const USER_URL = "users";
export const COMMENT_BY_POST_URL = "comments/post";
